### ISSUE TITLE
Crash in on android 9 (P)  when trying to open the settings dialog

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1142]
## Hardware

FxR running on Android 9 (P)
## Steps to Reproduce

1. Launch FxR
2. Touch the setting dialog button

## Current Behavior

FxR crashes.

## Expected Behavior

Settings dialog opens.

## Error Logs and Stack Traces

<details open>

```
2019-05-01 17:48:38.921 13863-13863/org.mozilla.vrbrowser E/VRB: Error creating child widget: null
2019-05-01 17:48:38.921 13863-13863/org.mozilla.vrbrowser W/System.err: java.lang.reflect.InvocationTargetException
2019-05-01 17:48:38.921 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2019-05-01 17:48:38.922 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2019-05-01 17:48:38.922 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.UIWidget.createChild(UIWidget.java:327)
2019-05-01 17:48:38.922 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.TrayWidget.toggleSettingsDialog(TrayWidget.java:256)
2019-05-01 17:48:38.922 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.TrayWidget.lambda$initialize$2$TrayWidget(TrayWidget.java:98)
2019-05-01 17:48:38.923 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.-$$Lambda$TrayWidget$oeFfPBLGEkHqwi7PK-MSpEegiyA.onClick(Unknown Source:2)
2019-05-01 17:48:38.923 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.performClick(View.java:6597)
2019-05-01 17:48:38.923 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.performClickInternal(View.java:6574)
2019-05-01 17:48:38.923 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.access$3100(View.java:778)
2019-05-01 17:48:38.923 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View$PerformClick.run(View.java:25885)
2019-05-01 17:48:38.923 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-05-01 17:48:38.924 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-05-01 17:48:38.924 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-05-01 17:48:38.924 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
2019-05-01 17:48:38.924 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-05-01 17:48:38.924 13863-13863/org.mozilla.vrbrowser W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-05-01 17:48:38.925 13863-13863/org.mozilla.vrbrowser W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-05-01 17:48:38.925 13863-13863/org.mozilla.vrbrowser W/System.err: Caused by: android.view.InflateException: Binary XML file line #156: Binary XML file line #156: Error inflating class <unknown>
2019-05-01 17:48:38.925 13863-13863/org.mozilla.vrbrowser W/System.err: Caused by: android.view.InflateException: Binary XML file line #156: Error inflating class <unknown>
2019-05-01 17:48:38.926 13863-13863/org.mozilla.vrbrowser W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2019-05-01 17:48:38.926 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2019-05-01 17:48:38.926 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2019-05-01 17:48:38.926 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
2019-05-01 17:48:38.926 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
2019-05-01 17:48:38.926 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
2019-05-01 17:48:38.927 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.inflate(View.java:24354)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.dialogs.SettingsWidget.initialize(SettingsWidget.java:88)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.dialogs.SettingsWidget.<init>(SettingsWidget.java:74)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.UIWidget.createChild(UIWidget.java:327)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.TrayWidget.toggleSettingsDialog(TrayWidget.java:256)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.TrayWidget.lambda$initialize$2$TrayWidget(TrayWidget.java:98)
2019-05-01 17:48:38.928 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.-$$Lambda$TrayWidget$oeFfPBLGEkHqwi7PK-MSpEegiyA.onClick(Unknown Source:2)
2019-05-01 17:48:38.929 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.performClick(View.java:6597)
2019-05-01 17:48:38.929 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.performClickInternal(View.java:6574)
2019-05-01 17:48:38.929 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.access$3100(View.java:778)
2019-05-01 17:48:38.929 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View$PerformClick.run(View.java:25885)
2019-05-01 17:48:38.929 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-05-01 17:48:38.933 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-05-01 17:48:38.933 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-05-01 17:48:38.933 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
2019-05-01 17:48:38.933 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-05-01 17:48:38.933 13863-13863/org.mozilla.vrbrowser W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-05-01 17:48:38.934 13863-13863/org.mozilla.vrbrowser W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-05-01 17:48:38.935 13863-13863/org.mozilla.vrbrowser W/System.err: Caused by: android.content.res.Resources$NotFoundException: Drawable org.mozilla.vrbrowser:drawable/ic_settings_controlleroptions with resource ID #0x7f0700aa
2019-05-01 17:48:38.936 13863-13863/org.mozilla.vrbrowser W/System.err: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_settings_controlleroptions.xml from drawable resource ID #0x7f0700aa
2019-05-01 17:48:38.936 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
2019-05-01 17:48:38.936 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
2019-05-01 17:48:38.936 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:897)
2019-05-01 17:48:38.936 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
2019-05-01 17:48:38.936 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
2019-05-01 17:48:38.936 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.views.HoneycombButton.<init>(HoneycombButton.java:37)
2019-05-01 17:48:38.937 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.views.HoneycombButton.<init>(HoneycombButton.java:29)
2019-05-01 17:48:38.937 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2019-05-01 17:48:38.937 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2019-05-01 17:48:38.937 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
2019-05-01 17:48:38.937 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
2019-05-01 17:48:38.939 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
2019-05-01 17:48:38.939 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
2019-05-01 17:48:38.939 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.939 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.939 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.940 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.940 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.940 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.940 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.940 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.941 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2019-05-01 17:48:38.941 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2019-05-01 17:48:38.941 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
2019-05-01 17:48:38.941 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
2019-05-01 17:48:38.941 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
2019-05-01 17:48:38.941 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.inflate(View.java:24354)
2019-05-01 17:48:38.941 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.dialogs.SettingsWidget.initialize(SettingsWidget.java:88)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.dialogs.SettingsWidget.<init>(SettingsWidget.java:74)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.UIWidget.createChild(UIWidget.java:327)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.TrayWidget.toggleSettingsDialog(TrayWidget.java:256)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.TrayWidget.lambda$initialize$2$TrayWidget(TrayWidget.java:98)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at org.mozilla.vrbrowser.ui.widgets.-$$Lambda$TrayWidget$oeFfPBLGEkHqwi7PK-MSpEegiyA.onClick(Unknown Source:2)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.performClick(View.java:6597)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.performClickInternal(View.java:6574)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View.access$3100(View.java:778)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.view.View$PerformClick.run(View.java:25885)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-05-01 17:48:38.942 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-05-01 17:48:38.943 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
2019-05-01 17:48:38.943 13863-13863/org.mozilla.vrbrowser W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-05-01 17:48:38.943 13863-13863/org.mozilla.vrbrowser W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-05-01 17:48:38.943 13863-13863/org.mozilla.vrbrowser W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-05-01 17:48:38.943 13863-13863/org.mozilla.vrbrowser W/System.err: Caused by: java.lang.IllegalArgumentException: c needs to be followed by a multiple of 6 floats. However, 7 float(s) are found. Failure occurred at position 102 of path: M198.3,40.5c-0.2,10.8 -3.8,20 -11.3,27.6c-3.9,4 -7.9,7.9 -11.8,11.8c-35.6,35.6 -71.2,71.3 -106.9,106.9c-6.5,6.5 -14.4,10 .3 -23.6,11.2c-20.9,2.2 -39.9,-12.5 -42.7,-33.2c-1.7,-12.1 1.7,-22.7 9.6,-31.8c0.3,-0.4 0.6,-0.7 1,-1C51.9,92.8 91,53.6 130.2,14.5c1.9,-1.9 3.8,-3.7 5.9,-5.2c22.7,-16.6 54.9,-4.8 61.2,23c0.3,1.4 0.5,2.8 0.7,4.2C198.2,37.9 198.3,39.3 198.3,40.5zM159.5,6.9c-18.9,0 -34.2,15.2 -34.3,34.1c0,18.6 14.9,33.6 33.6,33.7c18.9,0.1 34.3,-15.3 34.3,-34.2C193.2,21.9 178. 2,7 159.5,6.9zM84,128.3c7,0 12.6,-5.5 12.6,-12.4c0,-6.9 -5.6,-12.6 -12.5,-12.6c-6.9,0 -12.5,5.6 -12.5,12.5C71.6,122.8 77.1,128.3 84,128.3zM113.3,99c7.1,0 12.6,-5.5 12.6,-12.4c0,-6 .9 -5.6,-12.6 -12.5,-12.6c-6.9,0 -12.5,5.6 -12.5,12.5C101,93.4 106.5,99 113.3,99z
2019-05-01 17:48:38.943 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.util.PathParser.nCreatePathDataFromString(Native Method)
2019-05-01 17:48:38.943 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.util.PathParser.access$200(PathParser.java:24)
2019-05-01 17:48:38.944 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.util.PathParser$PathData.<init>(PathParser.java:76)
2019-05-01 17:48:38.944 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:2016)
2019-05-01 17:48:38.944 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1967)
2019-05-01 17:48:38.944 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.graphics.drawable.VectorDrawable.inflateChildElements(VectorDrawable.java:819)
2019-05-01 17:48:38.944 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:717)
2019-05-01 17:48:38.944 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
2019-05-01 17:48:38.945 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
2019-05-01 17:48:38.945 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
2019-05-01 17:48:38.945 13863-13863/org.mozilla.vrbrowser W/System.err:     at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)
2019-05-01 17:48:38.945 13863-13863/org.mozilla.vrbrowser W/System.err: 	... 45 more
2019-05-01 17:48:38.945 13863-13863/org.mozilla.vrbrowser E/VRB: Failed to create settings widget
```

</details>

**Comment by bluemarvin** [comment]
Using an older emulator Android N (7.1.1) API 25 worked. So we may have a bug on P.

**Comment by bluemarvin** [comment]
I can reproduce the issue on a Pixel 2 running android P with NoAPI Arm32. Looks like we have a bug on P and later.

**Comment by bluemarvin** [comment]
Unable to reproduce with latest version of FxR. Closing for now.

**Comment by MortimerGoro** [comment]
This crash was fixed in https://github.com/MozillaReality/FirefoxReality/commit/14c81cf29dbd86e5b64882281866ea8111b77e58

**Comment by Softvision-GeluHaiduc** [comment]
I will remove the QA label for now as there is nothing actionable by QA.
If QA attention is needed in the future please add the label again and we will address it.
