### ISSUE TITLE
FxR crashes upon requesting Voice Search for the first time with a fresh install

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1181]
## Hardware
Oculus Go

## Steps to Reproduce
1. Do a fresh install of FxR master.
2. Press the Microphone icon in the URL bar.
3. Notice FxR crashes and relaunches.
4. Once FxR launches, press the Microphone icon again, and notice that Voice Search correctly works without crashing.

## Current Behavior
Initiating Voice Search on a clean install causes FxR to crash, but it does not crash subsequent times.

## Expected Behavior
Initiating Voice Search on a clean install should not cause FxR to crash.

## Error Logs and Stack Traces
<details open>

<summary>Java Stack Trace</summary>

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at com.mozilla.speechlibrary.MozillaSpeechService.notifyListeners(MozillaSpeechService.java:75)
	at com.mozilla.speechlibrary.MozillaSpeechService.start(MozillaSpeechService.java:58)
	at org.mozilla.vrbrowser.ui.widgets.dialogs.VoiceSearchWidget.startVoiceSearch(VoiceSearchWidget.java:235)
	at org.mozilla.vrbrowser.ui.widgets.dialogs.VoiceSearchWidget.show(VoiceSearchWidget.java:279)
	at org.mozilla.vrbrowser.ui.widgets.UIWidget.show(UIWidget.java:251)
	at org.mozilla.vrbrowser.ui.widgets.dialogs.VoiceSearchWidget.onRequestPermissionsResult(VoiceSearchWidget.java:264)
	at org.mozilla.vrbrowser.VRBrowserActivity.lambda$onRequestPermissionsResult$44$VRBrowserActivity(VRBrowserActivity.java:1079)
	at org.mozilla.vrbrowser.-$$Lambda$VRBrowserActivity$YIsW9C3i9nPGcNe9k_hcQT4Whks.run(lambda)
	at android.app.Activity.runOnUiThread(Activity.java:5900)
	at org.mozilla.vrbrowser.VRBrowserActivity.onRequestPermissionsResult(VRBrowserActivity.java:1077)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7118)
	at android.app.Activity.dispatchActivityResult(Activity.java:6970)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4110)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4157)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6144)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

</details>

**Comment by philip-lamb** [comment]
Also on Vive Focus.
