### ISSUE TITLE
CMake Error in Android Studio Windows

### ISSUE THREAD

**Issue by 15102377525** [MozillaReality/FirefoxReality#1972]
Error configuring CMake server (D:\android\SDK\SDK\cmake\3.10.2.4988404\bin).

CMake Error at CMakeLists.txt:14 (add_library):

CMake Error at CMakeLists.txt:149 (target_link_libraries):

Configuring incomplete, errors occurred!

See also "E:/android/FirefoxReality-master/app/.externalNativeBuild/cmake/googlevrArmRelease/armeabi-v7a/CMakeFiles/CMakeOutput.log".

**Comment by 15102377525** [comment]
If you comment out  add_subdirectory(src/main/cpp/vrb/src/) , it will compile successfully.

**Comment by marulka** [comment]
> If you comment out add_subdirectory(src/main/cpp/vrb/src/) , it will compile successfully.

Did you placed the VRB library correctly in src/main/cpp/vrb ? If so, did you check the CMakeLists.txt of this lib project source?

**Comment by 15102377525** [comment]
When downloaded from GitHub (src / main / CPP / VRB / SRC /) the directory is empty。

CMake Error at CMakeLists.txt:13 (add_subdirectory):
E:/android/FirefoxReality-master/app/src/main/cpp/vrb/src
does not contain a CMakeLists.txt file.
Configuring incomplete, errors occurred!
See also "E:/android/FirefoxReality-master/app/.externalNativeBuild/cmake/oculusvrArmRelease/x86/CMakeFiles/CMakeOutput.log".

If I copy cmakelists.txt under the project directory, the above situation will appear.

**Comment by bluemarvin** [comment]
Sounds like you forgot this step `git submodule update --init --recursive` from the read me. VRB is a submodule.

**Comment by 15102377525** [comment]
Thanks,I've solved the problem by putting the VRB file in the project, but there was an error at runtime. I don't know how to solve it.
* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForGooglevrArm64Debug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process E:\android\FirefoxReality-master\app\build\intermediates\javac\googlevrArm64Debug\compileGooglevrArm64DebugJavaWithJavac\classes

**Comment by 15102377525** [comment]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForGooglevrArm64Debug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process E:\android\FirefoxReality-master\app\build\intermediates\javac\goog
levrArm64Debug\compileGooglevrArm64DebugJavaWithJavac\classes
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process E:\android\FirefoxReality-master\app\build\intermediates\javac\googlevrArm64Debug\compileGoogle
vrArm64DebugJavaWithJavac\classes
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:427)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        ... 42 more
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process E:\android\FirefoxReality-master\app\build\intermediates\javac\googlevrArm64Debug\compileGooglevrArm64DebugJavaWithJavac\classes
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:900)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:825)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$$Lambda$435/1419432597.call(Unknown Source)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
        at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:895)
        ... 2 more
Caused by: com.android.tools.r8.errors.Unreachable: Unexpected type adjustment from java.lang.Object to java.lang.String[]
        at com.android.tools.r8.ir.desugar.LambdaMainMethodSourceCode.adjustType(LambdaMainMethodSourceCode.java:372)
        at com.android.tools.r8.ir.desugar.LambdaMainMethodSourceCode.prepareReturnValue(LambdaMainMethodSourceCode.java:283)
        at com.android.tools.r8.ir.desugar.LambdaMainMethodSourceCode.prepareInstructions(LambdaMainMethodSourceCode.java:271)
        at com.android.tools.r8.ir.synthetic.SyntheticSourceCode.setUp(SyntheticSourceCode.java:152)
        at com.android.tools.r8.ir.conversion.IRBuilder.build(IRBuilder.java:365)
        at com.android.tools.r8.ir.synthetic.SynthesizedCode.buildIR(SynthesizedCode.java:43)
        at com.android.tools.r8.graph.DexEncodedMethod.buildIR(DexEncodedMethod.java:243)
        at com.android.tools.r8.ir.conversion.IRConverter.rewriteCode(IRConverter.java:631)
        at com.android.tools.r8.ir.conversion.IRConverter.processMethod(IRConverter.java:598)
        at com.android.tools.r8.ir.conversion.IRConverter.optimizeSynthesizedMethod(IRConverter.java:581)
        at com.android.tools.r8.ir.conversion.IRConverter$$Lambda$678/1255764157.accept(Unknown Source)
        at com.android.tools.r8.graph.DexClass.forEachMethodThrowing(DexClass.java:146)
        at com.android.tools.r8.ir.conversion.IRConverter.optimizeSynthesizedClass(IRConverter.java:573)
        at com.android.tools.r8.ir.desugar.LambdaRewriter.synthesizeLambdaClasses(LambdaRewriter.java:177)
        at com.android.tools.r8.ir.conversion.IRConverter.synthesizeLambdaClasses(IRConverter.java:247)
        at com.android.tools.r8.ir.conversion.IRConverter.convertToDex(IRConverter.java:275)
        at com.android.tools.r8.D8.optimize(D8.java:203)
        at com.android.tools.r8.D8.run(D8.java:163)
        at com.android.tools.r8.D8.lambda$run$1(D8.java:93)
        at com.android.tools.r8.D8$$Lambda$453/1375520891.run(Unknown Source)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:55)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
        at com.android.tools.r8.D8.run(D8.java:90)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
        ... 3 more
