### ISSUE TITLE
App crashes on window.open (tabs)

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2020]
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: 94c6c127e8bac27bd1c8a99537c5d13dc433052a

Hardware: 

## Steps to Reproduce

1. Go to https://www.w3schools.com/jsref/met_win_prompt.asp
2. Click on "Try it yourself"

## Current Behavior

App crashes

## Expected Behavior

A new session should be opened.

## Context

This only happens in the feature/tabs branch.

## Error Logs and Stack Traces

<details open>

```
2019-10-18 17:48:20.883 6589-6589/org.mozilla.vrbrowser.dev E/GeckoCrashHandler: >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 1 ("main")
    java.lang.IllegalArgumentException: Must use an unopened GeckoSession instance
        at org.mozilla.geckoview.GeckoSession$3.lambda$handleMessage$4$GeckoSession$3(GeckoSession.java:653)
        at org.mozilla.geckoview.-$$Lambda$GeckoSession$3$W-gnbhMMaqAcPHnPyqZS4Yh6QAs.accept(lambda)
        at org.mozilla.geckoview.GeckoResult.lambda$accept$0(GeckoResult.java:382)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$I3k4K0DCRrX6z4p5VGaRoaRBTZM.onValue(lambda)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:431)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6144)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

</details>

**Comment by MortimerGoro** [comment]
Closed via #2028
