### ISSUE TITLE
org.mozilla.gecko.InputMethods.getPreferredLanguages(InputMethods.java:6)

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2737]
## Configuration

Firefox Reality version: ad7761857c77e3871f418e26bb4e1fbf86b71a22
Firefox Reality build ID: ad7761857c77e3871f418e26bb4e1fbf86b71a22

Hardware: 
Quest

## Context

https://crash-stats.mozilla.com/report/index/3e90bc28-0cc7-41ee-b379-effa90200202

## Error Logs and Stack Traces

<details open>

```
java.lang.NullPointerException
	at org.mozilla.gecko.InputMethods.getPreferredLanguages(InputMethods.java:6)
	at org.mozilla.vrbrowser.VRBrowserActivity.onCreate(VRBrowserActivity.java:11)
	at android.app.Activity.performCreate(Activity.java:6724)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2740)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6144)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

</details>

**Comment by keianhzo** [comment]
I couldn’t manage to reproduce that one. It seems to crash in GV, at `InputMethods:getPreferredLanguages` but I don’t see that method in that class and also the buildId that the crash is using is `20200107215758` which we have never bundled.
