### ISSUE TITLE
The FxA account is disconnected and can not be logged back in after closing and reopening the device

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2924]
**[Affected Versions]:**
- Firefox Reality version 9 rc7 (b68f946).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.
- Have a valid FxA account.

**[Steps to reproduce]:**                                        
1. Connect to the FxA account from prerequisites.
2. Close the device and reopen it.
3. Reopen Firefox Reality app.
4. Click the Settings button and observe if the FxA account is logged in.
5. Click the "Sign Into Account" button and observe the behavior.

**[Expected results]:**
- Step 4: The FxA account is logged in.
- Step 5: The FxA login process is started.

**[Actual results]:**
- Step 4: The FxA account is logged out.
- Step 5: The FxA login process is NOT started, only the settings prompt is dismissed.

**[Notes]:**
- As a side effect of this issue, if the "Send Tab to Device" button is clicked, the background remains dimmed and a blank prompt seems to appear, that can not be accessed and also blocks the interaction with the browser window.
- On the HTC devices, this issue is also reproducible after a restart of the device.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1JPBSxldH3P7BU6rNxnQgG7I9rw1IDG9S).

**Comment by MortimerGoro** [comment]
I can reproduce this. I found this in the console:

`2020-03-05 11:04:47.189 2582-2716/org.mozilla.vrbrowser.dev E/FxaDeviceConstellation: Error while running: ensuring capabilities
    mozilla.appservices.fxaclient.FxaException$Network: Network error: Network error: Java error: "Expected thread 1 (\"main\"), but running on thread 175 (\"DefaultDispatcher-worker-2\")"
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43)
        at mozilla.appservices.fxaclient.FirefoxAccount.ensureCapabilities(FirefoxAccount.kt:919)
        at mozilla.components.service.fxa.FxaDeviceConstellation$ensureCapabilitiesAsync$1$1.invoke(FxaDeviceConstellation.kt:61)
        at mozilla.components.service.fxa.FxaDeviceConstellation$ensureCapabilitiesAsync$1$1.invoke(FxaDeviceConstellation.kt:33)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67)
        at mozilla.components.service.fxa.FxaDeviceConstellation$ensureCapabilitiesAsync$1.invokeSuspend(FxaDeviceConstellation.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
2020-03-05 11:04:47.190 2582-2694/org.mozilla.vrbrowser.dev W/FirefoxAccountStateMachine: Failed to ensure device capabilities. Stopping.`

**Comment by Softvision-RemusDranca** [comment]
I've tested this issue in the production version of the app and it's not reproducible.
Tested on HTC Vive Focus Plus (FxR v8.1) and Oculus Quest (FxR v8).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 9 rc8 (9350b40). The FxA account is no longer disconnected after rebooting the device. 

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
