### ISSUE TITLE
Crash loading a video

### ISSUE THREAD

**Issue by jdm** [MozillaReality/FirefoxReality#589]
## Hardware
Oculus Go

## Steps to Reproduce
1. Load http://download.blender.org/peach/trailer/trailer_400p.ogg in a local build.

## Current Behavior
The browser crashes. 

## Expected Behavior
A video? Not a crash, at least.

## Context
Hit this while testing video playback.

## Error Logs and Stack Traces
Logcat:
```
--------- beginning of crash
10-01 10:39:41.931  4070  4070 E AndroidRuntime: FATAL EXCEPTION: main
10-01 10:39:41.931  4070  4070 E AndroidRuntime: Process: org.mozilla.vrbrowser, PID: 4070
10-01 10:39:41.931  4070  4070 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at java.net.URI$Parser.parse(URI.java:3050)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at java.net.URI.<init>(URI.java:590)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at java.net.URI.create(URI.java:852)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at org.mozilla.vrbrowser.telemetry.TelemetryWrapper.addLoadToHistogram(TelemetryWrapper.java:180)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at org.mozilla.vrbrowser.SessionStore.onPageStop(SessionStore.java:886)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:442)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:432)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:79)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:344)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-01 10:39:41.931  4070  4070 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-01 10:39:41.932  4070  4089 D GeckoViewNavigation[C]: loadURI: uri=http://download.blender.org/peach/trailer/trailer_400p.ogg where=1 flags=0x1008
10-01 10:39:41.935  4070  4089 D GeckoViewProgress: onStateChange: isTopLevel=true, flags=0xf0001, status=NS_OK loadType=2097153
10-01 10:39:41.936  4070  4089 D GeckoViewProgress: onStateChange: uri=http://download.blender.org/peach/trailer/trailer_400p.ogg isSuccess=true isStart=true isStop=false
```

```
```

</details>

**Comment by bluemarvin** [comment]
@daoshengmu This looks like a telemetry crash from the stack. Please investigate.

**Comment by jdm** [comment]
This may have been related to trying to loading via the stop button, since that code appears to be called in response to stopping a load.

**Comment by daoshengmu** [comment]
@jdm. Could you pull the latest code and try again? The call stack is not the functions at the current source code. And we already have checked if the url is null, so it should not happen `'int java.lang.String.length()' on a null object reference`.

**Comment by keianhzo** [comment]
@daoshengmu @bluemarvin Not happening anymore on latest build, probably related to url encoding/decoding fixed in this commit recently https://github.com/MozillaReality/FirefoxReality/pull/577/commits/75751e57dfa759c969f95ebea10ab02786c9d542
