### ISSUE TITLE
SurfaceTexture errors on browser shutdown

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#665]
## Hardware
Oculus

## Steps to Reproduce
- Open FxR
- Click back on the controller and exit
- There are some SurfaceTexture errors in logcat

## Error Logs and Stack Traces

<details open>

```
2018-10-24 18:14:26.495 1570-1676/? I/PanelRenderLayer: ResetSurface 540 x 300 - shape:2 stereo:0
2018-10-24 18:14:27.733 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-14-25253-1] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.734 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.734 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.734 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.734 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-15-25253-2] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.735 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.735 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.735 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.735 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-16-25253-3] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.736 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.736 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.739 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.740 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-18-25253-5] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.741 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.741 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.741 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.742 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-14-25253-1] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.743 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.743 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.743 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.743 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-15-25253-2] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.744 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.749 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.749 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.749 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-16-25253-3] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.750 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.750 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.750 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.750 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-18-25253-5] updateTexImage: GLConsumer is abandoned!
2018-10-24 18:14:27.751 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
2018-10-24 18:14:27.751 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:244)
2018-10-24 18:14:27.751 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling UpdateResource in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:276
2018-10-24 18:14:27.788 25253-25286/org.mozilla.vrbrowser I/VRB: SurfaceTextureFactory::ShutdownGL
2018-10-24 18:14:27.788 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-14-25253-1] detachFromContext: abandoned GLConsumer
2018-10-24 18:14:27.789 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:270)
2018-10-24 18:14:27.789 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling ShutdownGL in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:307
2018-10-24 18:14:27.789 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-15-25253-2] detachFromContext: abandoned GLConsumer
2018-10-24 18:14:27.792 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:270)
2018-10-24 18:14:27.792 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling ShutdownGL in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:307
2018-10-24 18:14:27.792 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-16-25253-3] detachFromContext: abandoned GLConsumer
2018-10-24 18:14:27.793 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:270)
2018-10-24 18:14:27.793 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling ShutdownGL in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:307
2018-10-24 18:14:27.793 25253-25286/org.mozilla.vrbrowser E/GLConsumer: [SurfaceTexture-18-25253-5] detachFromContext: abandoned GLConsumer
2018-10-24 18:14:27.794 25253-25286/org.mozilla.vrbrowser W/System.err:     at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:270)
2018-10-24 18:14:27.794 25253-25286/org.mozilla.vrbrowser E/VRB: Java exception encountered when calling ShutdownGL in /Users/mortimer/Projects/FirefoxReality/app/src/main/cpp/vrb/src/SurfaceTextureFactory.cpp:307

```

</details>

**Comment by larsbergstrom** [comment]
@MortimerGoro Are we planning to do this for 1.1, or should I leave it in the backlog? Thanks!

**Comment by MortimerGoro** [comment]
They are not harmful errors.  I think we can at least mute them for v1.1 and work on the good fix for the backlog.

**Comment by larsbergstrom** [comment]
@MortimerGoro Great, thanks! Leaving in the backlog.
