### ISSUE TITLE
Crash upon loading navigation menu on Amazon.com

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#848]
## Hardware
Oculus Go
dcb38f3

## Steps to Reproduce
1. Launch https://amazon.com/.
2. Press the Navigation in the top-left corner (i.e., the hamburger menu icon).
3. Notice Firefox Reality crashes. ([See crash report on Socorro.](https://crash-stats.mozilla.com/report/index/13a1f2b9-af4f-4776-b41d-4d4440181127))

## Current Behavior
Firefox Reality crashes upon loading `JavaScript: (0)`. ([See crash report on Socorro for `java.net.URISyntaxException: at java.net.URI$Parser.fail(URI.java)`.](https://crash-stats.mozilla.com/report/index/13a1f2b9-af4f-4776-b41d-4d4440181127))

## Expected Behavior
Firefox Reality does not crash upon loading `JavaScript: (0)`.

## Context
Firefox Reality chokes on the URI, `JavaScript: (0)`, when it is parsed by the URL parsing logic in the UI-Override code (added in PR #777).

## Logs
[See crash report on Socorro.](https://crash-stats.mozilla.com/report/index/13a1f2b9-af4f-4776-b41d-4d4440181127)
Callstack:
```
java.net.URISyntaxException
	at java.net.URI$Parser.fail(URI.java:2856)
	at java.net.URI$Parser.checkChars(URI.java:3029)
	at java.net.URI$Parser.parse(URI.java:3066)
	at java.net.URI.<init>(URI.java:590)
	at java.net.URI.create(URI.java:852)
	at org.mozilla.vrbrowser.browser.UserAgentOverride.lookupOverride(UserAgentOverride.java:46)
	at org.mozilla.vrbrowser.browser.SessionStore.onLoadRequest(SessionStore.java:949)
	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:452)
	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:402)
	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:79)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6143)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by bluemarvin** [comment]
@cvan were you logged into amazon? I can't reproduce the crash.

**Comment by cvan** [comment]
> @cvan were you logged into amazon? I can't reproduce the crash.

nope, on a clean install.

you can reproduce by clicking the last link on https://webxr.sh/javascript-url

**Comment by bluemarvin** [comment]
Thanks, was able to reproduce crash and verified my PR fixes the issue.
